### ISSUE TITLE
Verify what needs to be installed

### ISSUE THREAD

**Issue by bdwyer2** [IBM/MAX-Image-Completer#28]
5e9c9cb4a777756f6c95200c86702a750312866e added the following packages: `g++`, `gcc`, `cmake`, `libsm6`, `libxext6`, `libxrender-dev`, `libglib2.0-dev`, `libc6-i386`

[Dockerfile#L3](https://github.com/IBM/MAX-Image-Completer/blob/master/Dockerfile#L3)

We should go through and verify that all these packages are actually required and remove the ones that aren't needed.

**Comment by xuhdev** [comment]
`libc6-i386` is a very odd dependency.

Also, we should surround the pip command with the following so that build dependencies do not stay:

    apt-get install -y build-essentials some-dev some-notdev && \
    pip install .... && \
    apt-get remove some-dev build-essentials && apt-get autoremove

**Comment by SSaishruthi** [comment]
@xuhdev 
Which pip command you are referring to?

**Comment by xuhdev** [comment]
pip install -r requirements.txt
